### ISSUE TITLE
Gravitational Attraction Figure 2.6

### ISSUE THREAD

**Issue by yinkou** [shiffman/The-Nature-of-Code-archive#275]
It's not really an issue but it bugs me every time i see it.  
There are two Vectors Fg pointing towards each other from the two masses.  
One of them should be -Fg since there are not the same! Even if it may confuse some beginners, it should get clear as they read and understand your n-body code.  
Or simply call them Fm1 and Fm2.

**Comment by shiffman** [comment]
Moved: https://github.com/shiffman/The-Nature-of-Code/issues/96
