### ISSUE TITLE
Confusing Paragraph in Section 9.6

### ISSUE THREAD

**Issue by eldavojohn** [shiffman/The-Nature-of-Code-archive#294]
Section 9.6 page 401 where it says "This strategy will produce essentially the same results..." that whole paragraph makes no sense to me at all.  I fail to see how the random midpoint and coin flipping method will produce essentially the same result or even give the same possible outcomes.  I can produce a trivial example where these will perform and behave quite differently but maybe I am missing something?

**Comment by shiffman** [comment]
I've changed the text to:

> This strategy will not change how the example behaves from the random midpoint method; however, if the order of the genetic information plays some role in expressing the phenotype, you may prefer one solution over the other.

Thank you!
