### ISSUE TITLE
Figure 1.7 vector length labels are wrong in the last picture

### ISSUE THREAD

**Issue by tjunnone** [shiffman/The-Nature-of-Code-archive#301]
In Figure 1.7, Vector Subtraction, the last (4th) vector image has the vector length labels swapped. 2 should be horizontal vector length, and -2 should be the vertical vector length.

**Comment by shiffman** [comment]
Moved to here: https://github.com/shiffman/The-Nature-of-Code/issues/97 Thank you!!
