### ISSUE TITLE
Random Walker canvas size mismatch

### ISSUE THREAD

**Issue by alignedleft** [shiffman/The-Nature-of-Code-archive#351]
A very minor mismatch between the text of the book and the example code:

In section I.2, when Example I.1 is introduced, `setup()` indicates:

```
  size(640,360);
```

…yet the dimensions in the Example I.1 code are different:

```
  size(800,200);
```

The latter is reflected (correctly) in the screenshot shown in the text shortly thereafter.

**Comment by shiffman** [comment]
Now tracked: https://github.com/shiffman/The-Nature-of-Code/issues/100
