### ISSUE TITLE
Please Create a tutorial video on Neural Networks

### ISSUE THREAD

**Issue by PalashTanejaPro** [shiffman/The-Nature-of-Code-archive#366]
Hi Daniel, 
I recently found out your tutorials on genetic algos. and I must admit that they are the best I found so far,
I certainly believe that a large amount of people would want your simplistic style of explanation for neural networks, I'm sorry for being a bit demanding but I would not be able to get a good grip on neural networks without your tutorials

**Comment by x87** [comment]
Here it is: https://youtu.be/XJ7HLz9VYz0
